@authUrl = http://localhost:3000/api/auth
@userURL = http://localhost:3000/api/user
@tugasURL =  http://localhost:3000/api/tugas
@contentType = application/json

### ========================================
### REGISTER USER (DEV)
### ========================================
POST {{authUrl}}/register
Content-Type: {{contentType}}

{
  "nama": "Andi",
  "nik": "3508123456789001",
  "no_telp": "081234567890",
  "password": "123456",
  "role": "driver"
}

### ========================================
### LOGIN
### ========================================
# @name login
POST {{authUrl}}/login
Content-Type: {{contentType}}

{
  "nama": "Driver Andi",
  "password": "123456"
}

### ========================================
### CHECK SESSION (ME)
### ========================================
GET {{authUrl}}/me
Content-Type: {{contentType}}
# Cookie: {{login.response.headers.Set-Cookie}}

### ========================================
### LOGOUT
### ========================================
POST {{authUrl}}/logout
Content-Type: {{contentType}}
# Cookie: {{login.response.headers.Set-Cookie}}

### ========================================
### CHECK SESSION SETELAH LOGOUT
### ========================================
GET {{authUrl}}/me
Content-Type: {{contentType}}
# Cookie: {{login.response.headers.Set-Cookie}}

### ========================================
### GET USER DATA DASHBOARD 
### ========================================
GET {{userURL}}/me
Content-Type: {{contentType}}
# Cookie: {{login.response.headers.Set-Cookie}}

### ========================================
### SEARCH HISTORY USER DATA  
### ========================================
GET {{tugasURL}}/search?search=SMA 1 JAKARTA
Content-Type: {{contentType}}
###
GET {{tugasURL}}/search?search=2026-04-26
Content-Type: {{contentType}}
###
GET {{tugasURL}}/search?search=SMA 7 YTTA
Content-Type: {{contentType}}
###
GET {{tugasURL}}/search?search=2027-04-26
Content-Type: {{contentType}}

### ========================================
### DETAIL TUGAS YANG SUDAH SELESAI
### ========================================
GET {{tugasURL}}/2/detail
Content-Type: {{contentType}}
# Cookie: {{login.response.headers.Set-Cookie}}

### ========================================
### LIST TUGAS TUGAS YANG SUDAH SELESAI
### ========================================
GET {{tugasURL}}/history/preview
Content-Type: {{contentType}}

### ========================================
### TUGAS TUGAS YANG SEDANG BERLANGSUNG
### ========================================
GET {{tugasURL}}/current
Content-Type: {{contentType}}

### ========================================
### SCAN PICKUP, di SPPG sebelum perjalanan
### ========================================
POST {{tugasURL}}/pickup
Content-Type: {{contentType}}
Cookie: {{login.response.headers.Set-Cookie}}

{
  "qr_code": "RUN-1",
  "latitude": -6.2000,
  "longitude": 106.8000
}

### ========================================
### SCAN DELIVERED (ke sekolah)
### ========================================
POST {{tugasURL}}/scan/delivered
Content-Type: {{contentType}}
Cookie: {{login.response.headers.Set-Cookie}}

{
  "qr_code": "RUN-8",
  "sekolah_id": 3,
  "latitude": -6.2100,
  "longitude": 106.8100
}