@authUrl = http://localhost:3000/api/auth
@userURL = http://localhost:3000/api/user
@baseURL =  http://localhost:3000/api
@contentType = application/json

### ========================================
### REGISTER USER (DEV)
### ========================================
POST {{authUrl}}/register
Content-Type: {{contentType}}

{
  "nama": "Andi",
  "nik": "3508123456789001",
  "no_telp": "081234567890",
  "password": "123456",
  "role": "driver"
}

### ========================================
### LOGIN
### ========================================
# @name login
POST {{authUrl}}/login
Content-Type: {{contentType}}

{
  "nama": "Driver Andi",
  "password": "123456"
}

### ========================================
### CHECK SESSION (ME)
### ========================================
GET {{authUrl}}/me
Content-Type: {{contentType}}
# Cookie: {{login.response.headers.Set-Cookie}}

### ========================================
### LOGOUT
### ========================================
POST {{authUrl}}/logout
Content-Type: {{contentType}}
# Cookie: {{login.response.headers.Set-Cookie}}

### ========================================
### CHECK SESSION SETELAH LOGOUT
### ========================================
GET {{authUrl}}/me
Content-Type: {{contentType}}
# Cookie: {{login.response.headers.Set-Cookie}}

### ========================================
### GET USER DATA DASHBOARD 
### ========================================
GET {{userURL}}/me
Content-Type: {{contentType}}
# Cookie: {{login.response.headers.Set-Cookie}}

### ========================================
### SEARCH HISTORY USER DATA  
### ========================================
GET {{baseURL}}/tugas/search?search=SMA 1 JAKARTA
Content-Type: {{contentType}}
###
GET {{baseURL}}/tugas/search?search=2026-04-26
Content-Type: {{contentType}}
###
GET {{baseURL}}/tugas/search?search=SMA 7 YTTA
Content-Type: {{contentType}}
###
GET {{baseURL}}/tugas/search?search=2027-04-26
Content-Type: {{contentType}}

### ========================================
### DETAIL TUGAS YANG SUDAH SELESAI
### ========================================
GET {{baseURL}}/tugas/8/detail
Content-Type: {{contentType}}
# Cookie: {{login.response.headers.Set-Cookie}}

### ========================================
### LIST TUGAS TUGAS YANG SUDAH SELESAI
### ========================================
GET {{baseURL}}/tugas/history/preview
Content-Type: {{contentType}}

### ========================================
### TUGAS TUGAS YANG SEDANG BERLANGSUNG
### ========================================
GET {{baseURL}}/tugas/current
Content-Type: {{contentType}}

### ========================================
### SCAN PICKUP, di SPPG sebelum perjalanan
### ========================================
POST {{baseURL}}/tugas/scan
Content-Type: {{contentType}}
Cookie: {{login.response.headers.Set-Cookie}}

{
  "qr_code": "RUN-1",
  "latitude": -6.2000,
  "longitude": 106.8000
}

### ========================================
### SCAN DELIVERED, di Sekolah
### ========================================
POST {{baseURL}}/tugas/scan
Content-Type: {{contentType}}
Cookie: {{login.response.headers.Set-Cookie}}

{
  "qr_code": "RUN-4",
  "latitude": -6.2100,
  "longitude": 106.8100
}
### ========================================
### notif tugas baru ke semua driver
### ========================================
POST {{baseURL}}/notif/send-tugas
Content-Type: application/json
Cookie: {{login.response.headers.Set-Cookie}}

{
  "tugas_id": "7",
  "judul": "Tugas Baru Hari Ini",
  "pesan": "Silakan mulai pengantaran ke sekolah tujuan"
}
### ========================================
### notif tugas baru ke semua driver
### ========================================
POST {{baseURL}}/notif/send-tugas
Content-Type: application/json
Cookie: {{login.response.headers.Set-Cookie}}

{
  "tugas_id": "7",
  "judul": "Tugas Baru Hari Ini",
  "pesan": "Silakan mulai pengantaran ke sekolah tujuan"
}
### ================================================================
### agar frontend bisa mengambil semua notif (send aatau pun unsend)
### ===============================================================
GET {{baseURL}}/notif/
Content-Type: application/json
Cookie: {{login.response.headers.Set-Cookie}}

### ========================================
### READ notif tugas
### ========================================
POST {{baseURL}}/notif/read
Content-Type: application/json
Cookie: {{login.response.headers.Set-Cookie}}

### ===================================================================================
### Check dari frd ada pesan baru yang belum terkirim tidak, lalu ngambil semua yng unsent
### ======================================================================================
GET {{baseURL}}/notif/unsent
Cookie: {{login.response.headers.Set-Cookie}}

###
POST {{baseURL}}/notif/mark-sent
Content-Type: application/json
Cookie: {{login.response.headers.Set-Cookie}}

{
  "ids": [5]
}